---
title: "Untitled"
author: "Claudia van der Zijden"
date: "17/05/2021"
output: html_document
---

Make sure you have:
Two personal repositories on github: one for your portfolio, one for the regular exercises.
One repo in the projecticum organisation, that you share with your partner.
Your local repositories are up to date with the main for all three of them.
A github project, with kanban board filled with issues connected to the projecticum repository.
One (separate!) .Rmd file for each of your projecticum assignments.
Three local (i.e. on your laptop) Rstudio projects: projecticum, portfolio and regular_assignments. (you may have given them other names, that’s fine)
Make a new folder within Mendeley for the projecticum. Place all pdf’s you used till now in your folder (if you did not use any papers as source yet, find 3 papers on Pubmed now that you could use for your introduction.). Copy your .bib file to the folder on your computer you are using for the Projecticum git repo.

__papers staan in mandely, rmd moet nog geschreven__ 

Start a .Rmd named “introduction.Rmd” with a few lines introduction on your projecticum topic.
Include automatic inline references to the papers you used.
The bibliography will be placed at the end of the document. Provide an appropriate header.
Merge your work with that of your projecticum partner through github. Solve all the problems you encounter. If github does not want to merge .bib files and you want a merged one, try here.
Find out how you can add websites as reference to Mendeley.
Write (so not “copy!”) at least 500 words of introduction for your projecticum project and use at least 5 references.